### ISSUE TITLE
JWT token refresh

### ISSUE THREAD

**Issue by JohnDing1995** [praqma-training/sonar#21]
Currently, the refresh of the JWT token has not yet been implemented. once the session expired, we need to authenticate again with google.

**Comment by ChristofferNissen** [comment]
The refresh logic should be implemented in the frontend. Currently, i just remove all credentials from frontend when i get an error back from the API. This should be changed to call refreshToken() when error code 422 is returned. Leaving this as a future note to my self.

**Comment by ChristofferNissen** [comment]
Implemented in the frontend
