### ISSUE TITLE
Create test data

### ISSUE THREAD

**Issue by sofusalbertsen** [praqma-training/sonar#3]
Should be in the format of:

{
Survey-date: 12/3/2020,
Persons:[{
Email:,
Office:,
Team-name:
Name:,
Proficiency_level:[
Git:’fundamental awarenes’,
docker:’expert’]
} ]
}

**Comment by surajneupane55** [comment]
- Remove real Name and Email address
- Clean empty fields
- Remove: "I don't know" response

**Comment by sofusalbertsen** [comment]
Reopened this to reflect the discussions in Slack.
We need two sets of test-data. Inbound, and outbound data.
I realise that we have two different types of test data:
A: Data that comes into the datastore; raw input from the survey
B: Data that the frontend fetches.
For B, I think that the original format still holds true (some modifications made from original:
```
{
Survey-date: 12/3/2020,
Persons:[{
Email:,
Office:,
Team-name:
Name:,
survey:[{
name:Git,
level:},
{
name:Docker,
level:}]
} ]
}
```

**Comment by JohnDing1995** [comment]
After discussed with @surajneupane55  this morning, we design the data flow for MVP as follows.

1. The authorized user upload the test data (CSV file) from frontend
2. When upload, frontend send a POST request to the cloud function, the request contains the CSV file
3. The cloud function triggered by the request, it will convert the CSV file to JSON file according to the format above. The JSON file could be stored to the Firestore directly.
4. Now we have the data in the Firestore. The frontend could get the data in 2 ways:
    1.   Read data by API [here] directly(https://cloud.google.com/firestore/docs/quickstart-mobile-web) (so no endpoint for getting data from backend)
    2.  Do filtering in cloud function and the frontend get the filtered data by GET request.

**Comment by sofusalbertsen** [comment]
Nice work guys!
One thing that I'm not sure is included here is the ability to transform the header of the CSV file before importing.
Or is that something that we deem out of scope for the tool because it is already so trivial to do by hand in e.g. excel?
As an example, I have create another CSV file, exported from SurveyPal so we can see the difference.
https://github.com/praqma-training/sonar/blob/master/test-data/surveypal-data-in.csv

**Comment by sofusalbertsen** [comment]
Will close this issue
