### ISSUE TITLE
Mock-up of the front-end

### ISSUE THREAD

**Issue by sofusalbertsen** [praqma-training/sonar#4]
Make a rough draft of the frontend

**Comment by sofusalbertsen** [comment]
Mockup on how the single person view could be.
![Screenshot from 2020-04-02 09-25-02](https://user-images.githubusercontent.com/4633181/78221669-16041600-74c4-11ea-95f5-160d8fc8149c.png)

**Comment by sofusalbertsen** [comment]
The way I envision the bar that could represent aggregated values on "team/country/overall" part. 

![Screenshot from 2020-04-01 15-15-21](https://user-images.githubusercontent.com/4633181/78221743-3af88900-74c4-11ea-804b-d2a39af6795e.png)

**Comment by JohnDing1995** [comment]
> Mockup on how the single person view could be.
> ![Screenshot from 2020-04-02 09-25-02](https://user-images.githubusercontent.com/4633181/78221669-16041600-74c4-11ea-95f5-160d8fc8149c.png)

What will the "overview" contain? Should it be a fold graph?

**Comment by sofusalbertsen** [comment]
@JohnDing1995 
I think they should be stacked with all the answers for a given tech for a given person:
Like this (I know we use other chart lib)
https://www.chartjs.org/samples/latest/charts/bar/stacked.html

**Comment by sofusalbertsen** [comment]
@sofusalbertsen make a mock up of the representation of:
Give me all persons with this keyword in this level

**Comment by sofusalbertsen** [comment]
@sofusalbertsen missing mockup
Give me all data, sortet by survey period

**Comment by sofusalbertsen** [comment]
Will close this general part. 
mockups can be found here:

https://github.com/praqma-training/sonar/tree/master/documentation/mockups
