### ISSUE TITLE
Reaserch about data storage

### ISSUE THREAD

**Issue by sofusalbertsen** [praqma-training/sonar#8]

**Comment by sofusalbertsen** [comment]
How do we store and retrieve data for the frontend.

**Comment by JohnDing1995** [comment]
The survey is done. My suggestion would be [Google Firestore](https://cloud.google.com/firestore/docs)

It is a NoSQL DB which provides API interfaces to both backend services (cloud functions) and [web frontend](https://firebase.google.com/docs/firestore/query-data/get-data).

There are collections in a Firestore which have "document" under it. each document is a JSON document. We could have each "collection" as a survey (could be named by date). While the "document" could be each user's survey response, named by the user ID(a good example could be eficode email). The content of each "document" includes k-v pair of the user's response on each answer. Then we could have another "collection" only for the user's info.

@sofusalbertsen Does it sound ok for you? If it ok I'll close the issue move to #11 and start designing the data structure.
